backend:
  name: github
  repo: DEFER286/RISE-D
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  # Akkaataa Haaraa: Motivational Speeches hundas JSON tokko keessatti kuusuuf
  - name: "motivation_data"
    label: "Motivational Speeches (JSON)"
    files:
      - label: "Barruulee Onnachiisoo Hunda"
        name: "motivation"
        file: "data/motivation.json"
        fields:
          - label: "Tarree Barruulee Onnachiisoo"
            name: "items"
            widget: "list"
            fields:
              - { label: "Mata-duree", name: "title", widget: "string" }
              - { label: "Guyyaa", name: "date", widget: "datetime" }
              - { label: "Barruu Onnachiisoo", name: "body", widget: "markdown" }
              - { label: "Photo", name: "image", widget: "image", required: false }

  # Inni Instructive Stories akkuma jirutti itti fufa
  - name: "instructive_data"
    label: "Instructive Stories (JSON)"
    files:
      - label: "Barruelee Barsiisoo Hunda"
        name: "stories"
        file: "data/stories.json"
        fields:
          - label: "Tarree Seenaawwanii (List of Stories)"
            name: "items"
            widget: "list"
            fields:
              - { label: "Mata-duree", name: "title", widget: "string" }
              - { label: "Guyyaa", name: "date", widget: "datetime" }
              - { label: "Barruu Barsiisoo", name: "body", widget: "markdown" }
              - { label: "Photo", name: "image", widget: "image", required: false }

  # Kutaa Haaraa: Gorsa Barnootaa
  - name: "education_data"
    label: "Gorsa Barnootaa (JSON)"
    files:
      - label: "Barruulee Gorsa Barnootaa Hunda"
        name: "education"
        file: "data/education.json"
        fields:
          - label: "Tarree Barruulee Gorsa Barnootaa"
            name: "items"
            widget: "list"
            fields:
              - { label: "Mata-duree", name: "title", widget: "string" }
              - { label: "Guyyaa", name: "date", widget: "datetime" }
              - { label: "Qabiyyee Barruu", name: "body", widget: "markdown" }
              - { label: "Photo", name: "image", widget: "image", required: false }
