backend:
  name: git-gateway
  branch: main

site_url: https://rise-design.netlify.app

media_folder: "images"
public_folder: "/images"

collections:
  # Akkaataa Haaraa: Motivational Speeches hundas JSON tokko keessatti kuusuuf
  - name: "motivation_data"
    label: "Motivational Speeches (JSON)"
    files:
      - label: "Barruulee Onnachiisoo Hunda"
        name: "motivation"
        file: "data/motivation.json"
        fields:
          - label: "Tarree Barruulee Onnachiisoo"
            name: "items"
            widget: "list"
            fields:
              - { label: "Mata-duree", name: "title", widget: "string" }
              - { label: "Guyyaa", name: "date", widget: "datetime" }
              - { label: "Barruu Onnachiisoo", name: "body", widget: "markdown" }

  # Inni Instructive Stories akkuma jirutti itti fufa
  - name: "instructive_data"
    label: "Instructive Stories (JSON)"
    files:
      - label: "Barruulee Barsiisoo Hunda"
        name: "stories"
        file: "data/stories.json"
        fields:
          - label: "Tarree Seenaawwanii (List of Stories)"
            name: "items"
            widget: "list"
            fields:
              - { label: "Mata-duree", name: "title", widget: "string" }
              - { label: "Guyyaa", name: "date", widget: "datetime" }
              - { label: "Barruu Barsiisoo", name: "body", widget: "markdown" }
              
